import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { NIST_PQC, CISA_PQC, NSA_PQC } from "./data";
import { pick } from "../data/i18n.js";
import { readableOn } from "./theme";

const esc = (s = "") =>
  String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

const REPORT_UI = {
  title: {
    en: "Quantum4Colorado — Organizational Readiness Report",
    es: "Quantum4Colorado — Informe de Preparación Organizacional",
  },
  subtitle: {
    en: "Post-Quantum Cryptography (PQC) readiness summary",
    es: "Resumen de preparación en criptografía poscuántica (PQC)",
  },
  orgType: { en: "Organization type:", es: "Tipo de organización:" },
  riskScore: { en: "Risk score:", es: "Puntaje de riesgo:" },
  riskTier: { en: "Risk tier:", es: "Nivel de riesgo:" },
  identifiedFactors: { en: "Identified risk factors", es: "Factores de riesgo identificados" },
  priorityActions: { en: "Priority action list", es: "Lista de acciones prioritarias" },
  resources: { en: "Resources:", es: "Recursos:" },
  footer: {
    en: "Generated by Quantum4Colorado — a nonpartisan civic resource built for the 2026 Congressional App Challenge (CO-06). This assessment is informational and not a substitute for professional cybersecurity advice.",
    es: "Generado por Quantum4Colorado — un recurso cívico no partidista creado para el Congressional App Challenge 2026 (CO-06). Esta evaluación es informativa y no sustituye el asesoramiento profesional en ciberseguridad.",
  },
};

function buildHtml(results, lang) {
  const t = (field) => pick(field, lang);
  const ui = (key) => t(REPORT_UI[key]);

  const factors = results.factors.map((f) => `<li>${esc(t(f))}</li>`).join("");
  const actions = results.priorityActions
    .map(
      (a) => `
      <li style="margin-bottom:12px">
        <div><strong>[${esc(t(a.priority))}] ${esc(t(a.title))}</strong></div>
        <div style="color:#2B2B2B">${esc(t(a.description))}</div>
        ${a.resource ? `<div style="color:#1A1AE5">${esc(t(a.resource.label))}: ${esc(a.resource.url)}</div>` : ""}
      </li>`
    )
    .join("");

  return `<!doctype html><html><head><meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    body { font-family: 'Archivo', -apple-system, Helvetica, Arial, sans-serif; color:#0A0A0A; padding:28px; }
    h1 { color:#1A1AE5; font-size:22px; margin:0; }
    h2 { font-size:16px; border-bottom:1px solid #0A0A0A; padding-bottom:4px; margin:22px 0 8px; }
    .head { border-bottom:2px solid #1A1AE5; padding-bottom:12px; margin-bottom:18px; }
    .muted { color:#2B2B2B; font-size:13px; }
    .tier { display:inline-block; padding:4px 12px; border:2px solid #0A0A0A; color:${readableOn(results.tier.color)}; background:${results.tier.color}; font-weight:800; font-size:13px; }
    ul { padding-left:18px; } li { margin-bottom:6px; font-size:13px; }
    .foot { border-top:1px solid #0A0A0A; margin-top:22px; padding-top:10px; color:#2B2B2B; font-size:11px; }
  </style></head><body>
    <div class="head">
      <h1>${esc(ui("title"))}</h1>
      <div class="muted">${esc(ui("subtitle"))}</div>
    </div>
    <p><strong>${esc(ui("orgType"))}</strong> ${esc(t(results.orgLabel))}<br/>
       <strong>${esc(ui("riskScore"))}</strong> ${results.score}/100<br/>
       <strong>${esc(ui("riskTier"))}</strong> <span class="tier">${esc(t(results.tier.name))}</span></p>
    <p style="font-size:14px">${esc(t(results.interpretation))}</p>
    <h2>${esc(ui("identifiedFactors"))}</h2>
    <ul>${factors}</ul>
    <h2>${esc(ui("priorityActions"))}</h2>
    <ol>${actions}</ol>
    <div class="foot">
      <div>${esc(ui("resources"))} ${NIST_PQC.url} &middot; ${CISA_PQC.url} &middot; ${NSA_PQC.url}</div>
      <div>${esc(ui("footer"))}</div>
    </div>
  </body></html>`;
}

/* Render the report to a PDF and open the native share sheet. `lang`
   defaults to "en" so existing call sites that haven't been updated yet
   keep working. */
export async function generateReport(results, lang = "en") {
  const html = buildHtml(results, lang);
  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { UTI: "com.adobe.pdf", mimeType: "application/pdf" });
  }
  return uri;
}
