import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { NIST_PQC, CISA_PQC, NSA_PQC } from "./data";

const esc = (s = "") =>
  String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

function buildHtml(results) {
  const factors = results.factors.map((f) => `<li>${esc(f)}</li>`).join("");
  const actions = results.priorityActions
    .map(
      (a) => `
      <li style="margin-bottom:12px">
        <div><strong>[${esc(a.priority)}] ${esc(a.title)}</strong></div>
        <div style="color:#4A5568">${esc(a.description)}</div>
        ${a.resource ? `<div style="color:#1B3A6B">${esc(a.resource.label)}: ${esc(a.resource.url)}</div>` : ""}
      </li>`
    )
    .join("");

  return `<!doctype html><html><head><meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    body { font-family: -apple-system, Roboto, Helvetica, Arial, sans-serif; color:#1A1A2E; padding:28px; }
    h1 { color:#1B3A6B; font-size:22px; margin:0; }
    h2 { font-size:16px; border-bottom:1px solid #E2E8F0; padding-bottom:4px; margin:22px 0 8px; }
    .head { border-bottom:2px solid #1B3A6B; padding-bottom:12px; margin-bottom:18px; }
    .muted { color:#4A5568; font-size:13px; }
    .tier { display:inline-block; padding:4px 12px; border-radius:999px; color:#fff; background:${results.tier.color}; font-weight:700; font-size:13px; }
    ul { padding-left:18px; } li { margin-bottom:6px; font-size:13px; }
    .foot { border-top:1px solid #E2E8F0; margin-top:22px; padding-top:10px; color:#4A5568; font-size:11px; }
  </style></head><body>
    <div class="head">
      <h1>Quantum4Colorado — Organizational Readiness Report</h1>
      <div class="muted">Post-Quantum Cryptography (PQC) readiness summary</div>
    </div>
    <p><strong>Organization type:</strong> ${esc(results.orgLabel)}<br/>
       <strong>Risk score:</strong> ${results.score}/100<br/>
       <strong>Risk tier:</strong> <span class="tier">${esc(results.tier.name)}</span></p>
    <p style="font-size:14px">${esc(results.interpretation)}</p>
    <h2>Identified risk factors</h2>
    <ul>${factors}</ul>
    <h2>Priority action list</h2>
    <ol>${actions}</ol>
    <div class="foot">
      <div>Resources: ${NIST_PQC.url} &middot; ${CISA_PQC.url} &middot; ${NSA_PQC.url}</div>
      <div>Generated by Quantum4Colorado — a nonpartisan civic resource built for the 2026 Congressional App Challenge (CO-06). This assessment is informational and not a substitute for professional cybersecurity advice.</div>
    </div>
  </body></html>`;
}

/* Render the report to a PDF and open the native share sheet. */
export async function generateReport(results) {
  const html = buildHtml(results);
  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { UTI: "com.adobe.pdf", mimeType: "application/pdf" });
  }
  return uri;
}
